### PR TITLE
Feature/create experiment row

### PR DESCRIPTION
**Pull request by connoratrug**
Basic feature complete

- upload snp and event files and pass subject gender ( move data to server)
- run experiment ( trigger script on server and poll for results)
- show updates ( basic updates while user is waiting)
- show results ( render pdf into view)
- results download ( link to result file)
- clear data btn ( remove data from server)

### CODE REVIEW

**Comment by MaxPostema** [comment]
- De linter vind nog een paar dingen
- Data-model readme heeft het over (eventFile, snpFile) ik denk dat het moet zijn: (event data, snp BAF dat)
- Als de job failed (door b.v. afwezigheid van openCPU) blijft hij wachten zonder weergave van error
- Na een error is pas weer verder te werken door een "harde refresh" van de pagina. De form/store resetten is wellicht vriendelijke naar de gebruiker.

**Comment by connoratrug** [comment]
> * De linter vind nog een paar dingen

done 
> * Data-model readme heeft het over (eventFile, snpFile) ik denk dat het moet zijn: (event data, snp BAF dat)

'eventFile', 'snpFile' are the field names , 'event data', snp 'BAF dat are labels' , i will fix the label 

> * Na een error is pas weer verder te werken door een "harde refresh" van de pagina. De form/store resetten is wellicht vriendelijke naar de gebruiker. 

I am not sure we would want the user to continue ..,

**Comment by MaxPostema** [comment]
I am not getting it to run the test successfully as app or proxy using the latest version of molgenis and this PR

Maybe add a e2e test that runs an experiment using random data?

`
2019-03-13_13:44:13.020 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> molgenisToken  [in nameless template at line 10, column 65]
`

`
2019-03-13_13:44:13.021 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> id  [in nameless template at line 10, column 88]
`

`
2019-03-13_13:44:13.021 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> outputFile  [in nameless template at line 30, column 72]
`

**Comment by connoratrug** [comment]
> I am not getting it to run the test successfully as app or proxy using the latest version of molgenis and this PR
> 
> Maybe add a e2e test that runs an experiment using random data?
> 
> `2019-03-13_13:44:13.020 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> molgenisToken [in nameless template at line 10, column 65]`
> 
> `2019-03-13_13:44:13.021 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> id [in nameless template at line 10, column 88]`
> 
> `2019-03-13_13:44:13.021 [molgenis-job-2] ERROR freemarker.runtime - Error executing FreeMarker template freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> outputFile [in nameless template at line 30, column 72]`

**Comment by fdlk** [comment]
Some leftover issues:
* I can start the calculator without specifying gender
* If you click away from the screen while the job is still running, there is no way to get back to it
* Does not result in useful result within 300 seconds. I think this is because of a curl issue where opencpu cannot access the data from molgenis.

**Pull request merged**
